# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\dev\python\pdfcount\src\resources\uixml\gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.8
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_pdfcount(object):
    def setupUi(self, pdfcount):
        pdfcount.setObjectName("pdfcount")
        pdfcount.resize(632, 451)
        self.centralwidget = QtWidgets.QWidget(pdfcount)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tblFiles = QtWidgets.QTableWidget(self.centralwidget)
        self.tblFiles.setAcceptDrops(True)
        self.tblFiles.setDragDropOverwriteMode(False)
        self.tblFiles.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.tblFiles.setColumnCount(3)
        self.tblFiles.setObjectName("tblFiles")
        self.tblFiles.setRowCount(0)
        self.verticalLayout.addWidget(self.tblFiles)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnWipe = QtWidgets.QPushButton(self.centralwidget)
        self.btnWipe.setObjectName("btnWipe")
        self.horizontalLayout.addWidget(self.btnWipe)
        self.btnCount = QtWidgets.QPushButton(self.centralwidget)
        self.btnCount.setObjectName("btnCount")
        self.horizontalLayout.addWidget(self.btnCount)
        self.verticalLayout.addLayout(self.horizontalLayout)
        pdfcount.setCentralWidget(self.centralwidget)

        self.retranslateUi(pdfcount)
        QtCore.QMetaObject.connectSlotsByName(pdfcount)

    def retranslateUi(self, pdfcount):
        _translate = QtCore.QCoreApplication.translate
        pdfcount.setWindowTitle(_translate("pdfcount", "PDFcount - count pdf pages"))
        self.btnWipe.setText(_translate("pdfcount", "wipe"))
        self.btnCount.setText(_translate("pdfcount", "count"))
